#!/usr/bin/env bash

docker info > /dev/null 2>&1

# Ensure that Docker is running...
if [ $? -ne 0 ]; then
    echo "Docker is not running."
    exit 1
fi

if [ "$#" -ne 1 ]
then
  echo "Usage: ./bootstrap <app_name>"
  exit 1
fi

docker run -i \
    --rm \
    -u node \
    -v "$(pwd)":/opt \
    -w /opt \
    node:latest \
    bash -c "npm init vite@latest $1 && cd $1 && npm install"

CYAN='\033[0;36m'
LIGHT_CYAN='\033[1;36m'
WHITE='\033[1;37m'
NC='\033[0m'

echo ""

if sudo -n true 2>/dev/null; then
    sudo chown -R $USER: .
else
    echo -e "${WHITE}Please provide your password so we can make some final adjustments to your application's permissions.${NC}"
    echo ""
    sudo chown -R $USER: .
    echo ""
    echo -e "${WHITE}Thank you! We hope you build something incredible."
fi
